on: push
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    
    - name: jc-tb
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.ftpip }}
        username: ${{ secrets.ftpusername }}
        password: ${{ secrets.ftppassword }}
        local-dir: ./
        server-dir: /135.148.30.9_27015/garrysmod/data/adv_duplicator/-public folder-/
        dangerous-clean-slate: true
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          README.md
